name: Metrics
on:
  # Schedule updates (every day at midnight Manchester time)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run it manually from the Actions tab
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: lukedunsmoto
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          
          # Plugins
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
          
          # The "Standout" Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
